[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["xushh"]

[dependencies]
url-scraper = "0.1.0"
reqwest = "0.9.2"
bitflags = "1.0.4"
crossbeam-channel = "0.2.6"
chrono = "0.4.6"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.13.0"
